### ISSUE TITLE
"Release scheduled for April 15th, 2021."

### ISSUE THREAD

**Issue by mhr** [A2Zadeh/starnet#1]
Hi,

I just came across your preprint and am really looking forward to the release of your code. Do you know when it will be ready for release?

**Comment by A2Zadeh** [comment]
Hi @mhr,

I apologize for the delays in release. I am currently working on the final version of the paper with new results. I probably won't be able to release prior to the NeurIPS deadline. The deadline of April 15th was a bit ambitious, so I will update it to June 15th.

**Comment by mhr** [comment]
No problem! I was just wondering. I look forward to the release and the final version of your paper!

**Comment by A2Zadeh** [comment]
Thank you for your kind understanding @mhr. Will make sure the final version is worth the wait :). Closing the issue for now.
